### ISSUE TITLE
Add `ApiClient` endpoint support 

### ISSUE THREAD

**Issue by tonymushah** [tonymushah/mangadex-api#11]
This [`ApiClient`](https://api.mangadex.org/docs/redoc.html#tag/ApiClient) endpoint has been added in Mangadex API `5.10.0`
There is no official announcement in the [`Mangadex Discord`](https://discord.gg/mangadex).
But we should implement it (even if i don`t know what it is)

## Tasks : 
Implements : 

- [x] #75

- [x] #78
- [x] #81
- [x] #83
- [x] #84
- [x] [`DELETE /client/{id}`](https://api.mangadex.org/docs/redoc.html#tag/ApiClient/operation/delete-apiclient) : Delete ApiClient
- [x] [`GET /client/{id}/secret`](https://api.mangadex.org/docs/redoc.html#tag/ApiClient/operation/get-apiclient-secret) : Get Secret for Client by ID
- [x] [`POST /client/{id}/secret`](https://api.mangadex.org/docs/redoc.html#tag/ApiClient/operation/post-regenerate-apiclient-secret) : Regenerate Client Secret
